const POLITICAL_BODY_TYPES = new Map<string, string>();

POLITICAL_BODY_TYPES.set("ASSEMBLEE_NATIONALE", "de l'assemblée Nationale");
POLITICAL_BODY_TYPES.set("MISSION_INFORMATION", "de cette mission d'information");
POLITICAL_BODY_TYPES.set("ASSEMBLEE_PARLEMENTAIRE_INTERNATIONALE", "de cette assemblée parlementaire internationale");
POLITICAL_BODY_TYPES.set("OFFICE_PARLEMENTAIRE_OU_DELEGATION_MIXTE", "de cet office parlementaire (ou délégation mixte)");
POLITICAL_BODY_TYPES.set("AUTRES_COMMISSIONS_PERMANENTES", "de cette commission permanente");
POLITICAL_BODY_TYPES.set("ORGANISME_EXTRA_PARLEMENTAIRE", "de cet organisme extra parlementaire");
POLITICAL_BODY_TYPES.set("COMMISSIONS_ENQUETES", "de cette commission d'enquête");
POLITICAL_BODY_TYPES.set("ORGANISME_INTERNATIONAL", "de cet organisme international");
POLITICAL_BODY_TYPES.set("COMMISSIONS_MIXTES_PARITAIRES", "de cette commission mixte paritaire");
POLITICAL_BODY_TYPES.set("AUTRES_CONSEILS", "de ce conseil");
POLITICAL_BODY_TYPES.set("COMMISSIONS_PERMANENTES_LEGISLATIVES", "de cette commission permanente législative");
POLITICAL_BODY_TYPES.set("CONSEIL_CONSTITUTIONNEL", "du conseil constitutionnel");
POLITICAL_BODY_TYPES.set("COMMISSIONS_SPECIALES", "de cette commission spéciale");
POLITICAL_BODY_TYPES.set("CONSEIL_ECONOMIQUE_SOCIAL_ENVIRONNEMENTAL", "de ce conseil économique, social et environnemental");
POLITICAL_BODY_TYPES.set("COUR_JUSTICE_REPUBLIQUE", "de la cour de la justice de la république");
POLITICAL_BODY_TYPES.set("SENAT", "du sénat");
POLITICAL_BODY_TYPES.set("DELEGATION_BUREAU", "de cette délégation");
POLITICAL_BODY_TYPES.set("MANDAT_EUROPEEN", "de ce mandat européen");
POLITICAL_BODY_TYPES.set("DELEGATION_PARLEMENTAIRE", "de cette délégation parlementaire");
POLITICAL_BODY_TYPES.set("MINISTERE", "de ce ministère");
POLITICAL_BODY_TYPES.set("GROUPE_AMITIE", "de ce groupe d'amitié");
POLITICAL_BODY_TYPES.set("PRESIDENCE_REPUBLIQUE", "de la présidence de la république");
POLITICAL_BODY_TYPES.set("GROUPE_ETUDES", "de ce groupe d'études");
POLITICAL_BODY_TYPES.set("ASSEMMBLEE_TOM", "de cette assemblée d'un Territoire d'Outre-Mer");
POLITICAL_BODY_TYPES.set("GROUPE_ETUDES_VOCATION_INTERNATIONALE", "de ce groupe d'études à vocation internationale");
POLITICAL_BODY_TYPES.set("CONSEIL_GENERAL_OU_DEPARTEMENTAL", "de ce conseil général ou départemental");
POLITICAL_BODY_TYPES.set("GROUPE_POLITIQUE", "de ce groupe politique");
POLITICAL_BODY_TYPES.set("CONSEIL_REGIONAL", "de ce conseil régional");
POLITICAL_BODY_TYPES.set("HAUTE_COUR_JUSTICE", "de la Haute Cour de justice");
POLITICAL_BODY_TYPES.set("INTERCOMMUNALITE", "de cette inter-communalité");
POLITICAL_BODY_TYPES.set("MISSIONS_INFO_COMMUNES", "de cette mission d'information commune");
POLITICAL_BODY_TYPES.set("CONSEIL_MUNICIPALE", "de ce conseil municipal");
POLITICAL_BODY_TYPES.set("MISSION_INFO_CONFERENCE_PRESIDENTS", "de cette mission d'information");
POLITICAL_BODY_TYPES.set("COMMISSION_SENAT", "de cette commission du sénat");
POLITICAL_BODY_TYPES.set("COMMISSION_SPECIALE_SENAT", "de cette commission spéciale du sénat");
POLITICAL_BODY_TYPES.set("CONFERENCE_PRESIDENTS", "de la conférence des présidents");
POLITICAL_BODY_TYPES.set("DELEGATION_SENATORIALE", "de cette délégation sénatoriale");
POLITICAL_BODY_TYPES.set("GOUVERNEMENT", "du gouvernement");
POLITICAL_BODY_TYPES.set("GROUPE_SENAT", "du groupe du sénat");
POLITICAL_BODY_TYPES.set("PARTI_POLITIQUE", "de ce parti politique");

export default POLITICAL_BODY_TYPES;